export const metaFields = {
  ID: "ID",
  RESEARCHER: "Name",
  WP: "WP",
  ACTIVITY: "Activity Name",
  STARTM: "Start Month",
  ENDM: "End Month/ Ongoing",
  COMPLETIONSTATUS: "ActivityStatus",
  LINKEDWP: "Collaborating WPs",
  SUPPORTINGWP: "Supporting WP",
  CATEGORY: "Activity Category",
  DESCRIPTION: "Activity description",
  QUESTION: "Research questions",
  QTYPE: "Research Question type",
  QTYPE2: "Research Question type 2",
  METHOD: "Methodology",
  METHODCATEGORY: "Methodology category",
  DATATYPE: "Data Types and Procurement",
  DATACOLLECTED: "Collected",
  DATAGENERATED: "Generated",
  DATAMETHOD: "Data Procurement Method",
  DATAUSAGE: "Data Usage",
  PDCA: "PDCA Cycle",
  ENDUSER: "End Users",
  WATERPRODUCERS: "Water producers",
  RESEARCH: "Researchers",
  WATERUSERS: "Water users",
  CONTRIBUTIONS: "Contributions to Theory and Practice",
  THEORY: "THEORY",
  PRACTICE: "PRACTICE",
  PROJECTCONTRIBUTION: "Contribution to DU",
  TECHPLATFORM: "Technology platforms",
  POLICYSUPPORT: "Policy Support and Guidance",
  COLLAB: "Dissemination and Collaboration",
  PERSPECTIVES: "Specific Disciplinary perspectives",
  DISCIPLINEPERSPECTIVE: "Specific Disciplinary perspectives",
  DISCIPLINE: "Discipline",
  TDPERSPECTIVE: "Transdisciplinary perspectives",
  THEMATIC: "Thematic",
  METHODOLOGICAL: "Methodological",
  CONTRIBUTIONFIELD: "Fields of Scientific Contribution",
  IW: "IW Aims and Objectives",
  IWCONTRIBUTION: "Contributions to IW aims and objectives",
};
